const CurrencyCountryMap = new Map<string | undefined,string | undefined>([

['AUD','Australische Dollar'],
['BGN','Bulgarischer Lew'],
['BRL','Brasilianischer Real'],
['CAD','Kanadischer Dollar'],
['CHF','Schweizer Franken'],
['CNY','Chinesischer Yuan'],
['CZK','Tschechische Krone'],
['DKK','Dänische Krone'],
['EUR','Euro'],
['GBP','Britische Pfund'],
['HKD','Honkong Dollar'],
['HRK','Kroatische Kuna'],
['HUF','Ungarischer Forint'],
['IDR','Indonesische Rupiah'],
['ILS','Israelische Schekel'],
['INR','Indische Rupie'],
['ISK','Isländische Krone'],
['JPY','Japanischer Yen'],
['KRW','Südkoreanischer Won'],
['MXN','Mexikanischer Peso'],
['MYR','Malaisischer Ringgit'],
['NOK','Norwegische Krone'],
['NZD','Neuseeländische Dollar'],
['PHP','Philippinischer Peso'],
['PLN','Polnischer Zloty'],
['RON','Rumänischer Leu'],
['RUB','Russische Rubel'],
['SEK','Schwedische Krone'],
['SGD','Singapur Dollar'],
['THB','Thailändischer Baht'],
['TRY','Türkische Lira'],
['USD','US Dollar'],
['ZAR','Südafrikanischer Rand']
]);
export default CurrencyCountryMap;